language: node_js
before_install:
  - cd subdirectory
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - CI=false npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master